### ISSUE TITLE
Siteswap generator app gets crashed.

### ISSUE THREAD

**Issue by Sammaz2** [namlit/siteswap_generator#34]
### Actual behavior
When i opened the app and after that i started editing the blanks and then i scrolled down and then i activated the random generation mode and after that i set Pattern filter instead of number filter. And then i clicked on zips, zaps and holds. Turning zaps and holds of off. While as zips on. Then i clicked on the reset filters. After that i clicked on the numbers e.g no 4 , no 5 , at least 1 , no 3. I clicked on one of them. And suddenly the app crashed.

### How to reproduce

* First you need to download the app from fdroid.

* Install the app.

* Open the app.

* Edit the given blanks.

* Then select one of the filters zips, zaps or holds. And then click on reset filters after that click on one of the numbers. Suddenly the app will crash.

https://youtu.be/nwVh7sJY0Zk 

* Browser:siteswap generator.

* Version:1.0.4-beta

* Operating system:7.1.2

* Device model: Redmi 4

**Comment by namlit** [comment]
Hi, thank you for the report. That has probably something to do with the toasts, warning for invalid input values. I created a new issue #35 to remove that toasts and added it to the v1.1 milestone.
